---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'debian/**'
      - 'doc/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'debian/**'
      - 'doc/**'
    branches:
      - master

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1

      - name: Install dependencies
        run: |
          sudo apt install -y \
            libfmt-dev \
            libsystemd-dev \
            libluajit-5.1-dev \
            libgtest-dev

      - name: Meson Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          setup-options: -Ddocumentation=disabled
          meson-version: 0.56.0
